export type SettingSource = { kind: "local"; value: unknown } | { kind: "https"; url: string } | { kind: "home-assistant"; url: string; entity: string };
export interface ScheduleRule { id: string; label: string; enabled: boolean; weekdays: number[] | "every-day"; startTime: string; endTime: string; startDate?: string; endDate?: string; priority: number; values: Record<string, unknown>; source: SettingSource; }
export function validateSchedule(rule: ScheduleRule): void { if (!rule.id || !rule.label || !/^([01]\d|2[0-3]):[0-5]\d$/.test(rule.startTime) || !/^([01]\d|2[0-3]):[0-5]\d$/.test(rule.endTime)) throw new Error("Schedule requires valid identifiers and local times"); if (rule.weekdays !== "every-day" && (!rule.weekdays.length || rule.weekdays.some(day => !Number.isInteger(day) || day < 0 || day > 6))) throw new Error("Schedule weekdays are invalid"); if (rule.startDate && rule.endDate && rule.startDate > rule.endDate) throw new Error("Schedule date range is reversed"); if (rule.source.kind !== "local" && !/^https:\/\/[^/]+/.test(rule.source.url)) throw new Error("External setting sources require HTTPS"); }
export function scheduleMatches(rule: ScheduleRule, date: Date): boolean { if (!rule.enabled) return false; const day = date.getDay(); if (rule.weekdays !== "every-day" && !rule.weekdays.includes(day)) return false; const minutes = date.getHours() * 60 + date.getMinutes(), start = Number(rule.startTime.slice(0, 2)) * 60 + Number(rule.startTime.slice(3)), end = Number(rule.endTime.slice(0, 2)) * 60 + Number(rule.endTime.slice(3)); const time = start <= end ? minutes >= start && minutes <= end : minutes >= start || minutes <= end; return time && (!rule.startDate || date.toISOString().slice(0, 10) >= rule.startDate) && (!rule.endDate || date.toISOString().slice(0, 10) <= rule.endDate); }
export function resolveSchedules(rules: readonly ScheduleRule[], date: Date): Record<string, unknown> { return rules.filter(rule => scheduleMatches(rule, date)).sort((a, b) => b.priority - a.priority || a.id.localeCompare(b.id)).reduce((values, rule) => ({ ...values, ...rule.values }), {}); }
export type AdhdMode = "focus" | "low-stimulation" | "time-awareness" | "one-thing-at-a-time" | "momentum";
export const ADHD_MODES: readonly AdhdMode[] = ["focus", "low-stimulation", "time-awareness", "one-thing-at-a-time", "momentum"];
export type AdhdState = Record<AdhdMode, boolean>;
export const DEFAULT_ADHD_STATE: AdhdState = { focus: false, "low-stimulation": false, "time-awareness": false, "one-thing-at-a-time": false, momentum: false };
export function updateAdhd(state: AdhdState, mode: AdhdMode, enabled: boolean): AdhdState { return { ...state, [mode]: enabled }; }
export type ExportFormat = "json" | "jsonl" | "yaml" | "toml" | "xml" | "csv" | "tsv" | "markdown" | "html" | "sql" | "typescript" | "json-schema" | "protobuf" | "zip" | "7z";
export interface ExportCapability { format: ExportFormat; available: boolean; reason: string; }
export function exportCapability(format: ExportFormat, available = false): ExportCapability { return { format, available, reason: available ? "Implemented by the owning adapter" : "Pending format-specific owning adapter" }; }
export interface BulkPreview<T> { selected: number; affected: number; excluded: Array<{ item: T; reason: string }>; }
export function previewBulk<T>(items: readonly T[], selected: readonly T[], canApply: (item: T) => boolean): BulkPreview<T> { const excluded = selected.filter(item => !canApply(item)).map(item => ({ item, reason: "Action is unavailable for this item" })); return { selected: selected.length, affected: selected.length - excluded.length, excluded }; }
