import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { readZipMigrationArchive } from "../src/index";

function crc32(bytes: Uint8Array): number { let crc = 0xffffffff; for (const byte of bytes) { crc ^= byte; for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1)); } return (crc ^ 0xffffffff) >>> 0; }
function storedZip(entries: Array<{ name: string; bytes: Uint8Array }>): Buffer { const local: Buffer[] = []; const central: Buffer[] = []; let offset = 0; for (const entry of entries) { const name = Buffer.from(entry.name); const data = Buffer.from(entry.bytes); const crc = crc32(data); const header = Buffer.alloc(30); header.writeUInt32LE(0x04034b50, 0); header.writeUInt16LE(20, 4); header.writeUInt16LE(0x800, 6); header.writeUInt16LE(0, 8); header.writeUInt32LE(crc, 14); header.writeUInt32LE(data.length, 18); header.writeUInt32LE(data.length, 22); header.writeUInt16LE(name.length, 26); local.push(header, name, data); const record = Buffer.alloc(46); record.writeUInt32LE(0x02014b50, 0); record.writeUInt16LE(20, 4); record.writeUInt16LE(20, 6); record.writeUInt16LE(0x800, 8); record.writeUInt32LE(crc, 16); record.writeUInt32LE(data.length, 20); record.writeUInt32LE(data.length, 24); record.writeUInt16LE(name.length, 28); record.writeUInt32LE(0, 38); record.writeUInt32LE(offset, 42); central.push(record, name); offset += header.length + name.length + data.length; } const directory = Buffer.concat(central); const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10); end.writeUInt32LE(directory.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...local, directory, end]); }

async function run(): Promise<void> { const root = await mkdtemp(path.join(os.tmpdir(), "claude-design-zip-")); try { const project = Buffer.from(JSON.stringify({ name: "ZIP project", ownerKey: "owner" })); const content = Buffer.from("binary\u0000bytes", "utf8"); const hashes = { "projects/p1/project.json": createHash("sha256").update(project).digest("hex"), "projects/p1/files/data.bin": createHash("sha256").update(content).digest("hex") }; const manifest = Buffer.from(JSON.stringify({ format: "claude-design-desktop-import-v1", schemaVersion: 1, sourceProductVersion: "0.1.0", sourceCommit: "4a3c267e7e22f6636a02542554309cd49cd41e9d", sourceDatabaseSha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", exportedAt: new Date().toISOString(), idempotencyKey: "zip-1", recordCounts: { projects: 1, files: 1 }, exclusionCounts: {}, fileHashes: hashes })); const archivePath = path.join(root, "import.zip"); await writeFile(archivePath, storedZip([{ name: "manifest.json", bytes: manifest }, { name: "projects/p1/project.json", bytes: project }, { name: "projects/p1/files/data.bin", bytes: content }])); const archive = await readZipMigrationArchive(archivePath); assert.equal(archive.manifest.idempotencyKey, "zip-1"); const entries = [...archive.entries as Iterable<{ name: string; bytes: Uint8Array }>]; assert.deepEqual([...entries.find((entry) => entry.name.endsWith("data.bin"))!.bytes], [...content]); } finally { await rm(root, { recursive: true, force: true }); } }
void run();
