export type ProjectRole = "owner" | "editor" | "commenter" | "viewer";
export type ProjectType = "project" | "template" | "design-system";
export type DesignSharing = { scope: "invited" | "org" | "public"; linkPermission: "view" | "comment" | "edit"; teamCanComment: boolean; teamCanEdit: boolean; viewMode: "private" | "org" | "public" };
export type DesignProject = { id: string; uuid: string; name: string; title: string; description: string; type: ProjectType; ownerAccountId: string; createdAt: string; updatedAt: string; canEdit: boolean; sharing: DesignSharing; members: DesignMember[]; fileCount: number; dashboardHtml?: string; model?: string };
export type DesignMember = { accountId: string; email: string; displayName?: string; role: Exclude<ProjectRole, "owner"> };
export type DesignFile = { projectId: string; path: string; content: Uint8Array; contentType: string; createdAt: string; updatedAt: string; version: number };
export type DesignMessage = { id: string; chatId: string; role: "user" | "assistant" | "system"; content: string; createdAt: string; timestamp: string };
export type DesignAsset = { uuid: string; projectId: string; name: string; path: string; section: string; status: string; subtitle: string; chatId?: string; viewport?: Record<string, unknown> };
export type RequestContext = { accountId: string; capabilityValid?: boolean; transport: "ipc" | "rest" | "json" | "connect" | "mcp" };
export type CreateProjectInput = { name: string; description?: string; introText?: string; templateId?: string; templateTitle?: string; type?: ProjectType; model?: string; dashboardHtml?: string };
export type UpdateProjectInput = Partial<Pick<CreateProjectInput, "name" | "description" | "model" | "dashboardHtml">>;
export type WriteFileInput = { path: string; content: Uint8Array; contentType?: string; ifMatch?: string };
export type CopyFileInput = { srcProjectId?: string; src: string; dest: string; ifMatch?: string };
export type DomainPreview = { projectId: string; path: string; contentType: string; render: string; validators: string[]; url: string };
export type DesignDomain = { listProjects(c: RequestContext, t?: ProjectType): Promise<DesignProject[]>; getProject(c: RequestContext, id: string, messages?: boolean): Promise<DesignProject & { messages?: DesignMessage[] }>; createProject(c: RequestContext, i: CreateProjectInput): Promise<DesignProject>; updateProject(c: RequestContext, id: string, i: UpdateProjectInput): Promise<DesignProject>; deleteProject(c: RequestContext, id: string): Promise<void>; listFiles(c: RequestContext, id: string, path?: string, depth?: number, filter?: string): Promise<DesignFile[]>; readFile(c: RequestContext, id: string, path: string): Promise<DesignFile>; writeFiles(c: RequestContext, id: string, files: WriteFileInput[], deletes?: string[], deduplicate?: boolean): Promise<{ files: DesignFile[]; deleted: number }>; copyFiles(c: RequestContext, id: string, files: CopyFileInput[]): Promise<{ files: DesignFile[] }>; deleteFiles(c: RequestContext, id: string, paths: string[]): Promise<{ deleted: number; paths: string[] }>; listMessages(c: RequestContext, id: string, chatId?: string): Promise<DesignMessage[]>; putMessages(c: RequestContext, id: string, messages: Array<Pick<DesignMessage, "role" | "content">>, title?: string): Promise<DesignMessage[]>; appendMessage(c: RequestContext, id: string, text: string, chatId?: string): Promise<{ messages: DesignMessage[]; assistant?: DesignMessage; files: DesignFile[] }>; listMembers(c: RequestContext, id: string): Promise<DesignMember[]>; addMember(c: RequestContext, id: string, m: Omit<DesignMember, "displayName">): Promise<DesignMember>; updateMemberRole(c: RequestContext, id: string, accountId: string, role: Exclude<ProjectRole, "owner">): Promise<DesignMember>; removeMember(c: RequestContext, id: string, accountId: string): Promise<boolean>; updateSharing(c: RequestContext, id: string, s: Pick<DesignSharing, "scope" | "linkPermission">): Promise<DesignSharing>; listDesignSystems(c: RequestContext): Promise<DesignProject[]>; recordAsset(c: RequestContext, a: Omit<DesignAsset, "uuid">): Promise<DesignAsset>; deleteAsset(c: RequestContext, id: string, name: string, path?: string): Promise<boolean>; renderPreview(c: RequestContext, id: string, path?: string, render?: string, validators?: string[]): Promise<DomainPreview>; createSupportJs(c: RequestContext, id: string, path?: string, ifMatch?: string): Promise<DesignFile> };
export class DomainError extends Error { constructor(readonly message: string, readonly status = 400, readonly code = "invalid_request", readonly details?: Record<string, unknown>) { super(message); this.name = "DomainError"; } }
export const ROLE_PERMISSIONS: Record<ProjectRole, ReadonlySet<string>> = { owner: new Set(["read", "comment", "write", "generate", "members", "sharing", "delete", "export"]), editor: new Set(["read", "comment", "write", "generate", "export"]), commenter: new Set(["read", "comment", "export"]), viewer: new Set(["read", "export"]) };
export function assertRole(role: ProjectRole | undefined, permission: string): asserts role is ProjectRole { if (!role || !ROLE_PERMISSIONS[role].has(permission)) throw new DomainError(`Project role does not permit ${permission}.`, 403, "forbidden"); }
export function normalizeProjectType(v: unknown): ProjectType | undefined { if (["project", "PROJECT_TYPE_PROJECT", 1, "1"].includes(v as never)) return "project"; if (["template", "PROJECT_TYPE_TEMPLATE", 2, "2"].includes(v as never)) return "template"; if (["design-system", "design_system", "PROJECT_TYPE_DESIGN_SYSTEM", 3, "3"].includes(v as never)) return "design-system"; return undefined; }
export function projectTypeName(t: ProjectType) { return t === "design-system" ? "PROJECT_TYPE_DESIGN_SYSTEM" : t === "template" ? "PROJECT_TYPE_TEMPLATE" : "PROJECT_TYPE_PROJECT"; }
export function normalizeProjectRole(v: unknown): Exclude<ProjectRole, "owner"> { if (v === "viewer" || v === "commenter" || v === "editor") return v; throw new DomainError("role must be viewer, commenter, or editor.", 400, "invalid_role"); }
export function normalizeSharingScope(v: unknown): DesignSharing["scope"] { return v === "org" || v === "public" ? v : "invited"; }
export function normalizeLinkPermission(v: unknown): DesignSharing["linkPermission"] { return v === "comment" || v === "edit" ? v : "view"; }
