import { DesignDomain, DomainError, RequestContext, normalizeProjectType, projectTypeName } from "./domain";
import { normalizeProjectPath } from "./path-policy";
export const JSON_SYNC_PREFIX = "/v1/design/anthropic.omelette.api.v1alpha.OmeletteService/";
export type JsonSyncRequest = { method: string; path: string; body?: Record<string, any> };
export type JsonSyncResponse = { status: number; body: unknown };
export type JsonSyncOptions = { accountId?: string; resolveAccount?: (transport: "json") => Promise<{ accountId: string; authenticated: boolean }> };
const idOf = (b: any) => { const id = b.projectId || b.project_id; if (typeof id !== "string" || !id) throw new DomainError("projectId is required.", 400, "invalid_project"); return id; };
const JSON_FIELDS = new Set(["chatId", "chat_id", "content", "contentBase64", "contentType", "content_type", "data", "deduplicate", "deletePaths", "depth", "description", "file", "files", "filter", "group", "introText", "intro_text", "isBase64", "is_base64", "limit", "mimeType", "name", "offset", "path", "projectId", "project_id", "projectType", "project_type", "raw", "scope", "section", "status", "subtitle", "templateId", "template_id", "templateTitle", "template_title", "text", "type", "viewport", "body", "bodyBase64", "encoding"]);
const project = (p: any) => ({ id: p.id, uuid: p.uuid, projectId: p.id, project_id: p.id, name: p.name, title: p.title, description: p.description, type: projectTypeName(p.type), projectType: projectTypeName(p.type), project_type: p.type === "design-system" ? 3 : p.type === "template" ? 2 : 1, typeName: projectTypeName(p.type), ownerAccountId: p.ownerAccountId, createdAt: p.createdAt, created_at: p.createdAt, updatedAt: p.updatedAt, updated_at: p.updatedAt, fileCount: p.fileCount, file_count: p.fileCount, canEdit: p.canEdit, can_edit: p.canEdit, sharing: { link_permission: p.sharing.linkPermission, scope: p.sharing.scope, team_can_comment: p.sharing.teamCanComment, team_can_edit: p.sharing.teamCanEdit, view_mode: p.sharing.viewMode } });
const file = (f: any) => ({ path: f.path, name: f.path.split("/").pop() || f.path, content: Buffer.from(f.content).toString("base64"), contentBase64: Buffer.from(f.content).toString("base64"), contentType: f.contentType, content_type: f.contentType, isBase64: true, is_base64: true, projectId: f.projectId, project_id: f.projectId, size: f.content.byteLength, version: f.version, updatedAt: f.updatedAt, updated_at: f.updatedAt });
export async function handleJsonSyncRequest(domain: DesignDomain, request: JsonSyncRequest, options: JsonSyncOptions): Promise<JsonSyncResponse> {
  if (request.method.toUpperCase() !== "POST") return { status: 405, body: { error: { message: "Design sync JSON RPC only supports POST." } } };
  const path = request.path.replace(/\?.*$/, ""); if (!path.startsWith(JSON_SYNC_PREFIX)) return { status: 404, body: { error: { message: "Unknown Design sync JSON route." } } };
  if (!request.body || typeof request.body !== "object" || Array.isArray(request.body)) return { status: 400, body: { error: { code: "invalid_body", message: "The Design sync body must be a JSON object." } } };
  const b = request.body; for (const key of Object.keys(b)) if (!JSON_FIELDS.has(key)) return { status: 400, body: { error: { code: "unknown_field", message: `Unsupported Design sync field: ${key}.` } } };
  const account = options.resolveAccount ? await options.resolveAccount("json") : { accountId: options.accountId || "", authenticated: Boolean(options.accountId) }; if (!account.authenticated || !account.accountId) return { status: 401, body: { error: { code: "account_required", message: "An authenticated account is required." } } }; const c: RequestContext = { accountId: account.accountId, capabilityValid: true, transport: "json" };
  try {
    switch (path.slice(JSON_SYNC_PREFIX.length)) {
      case "ListOrgProjects": { const items = (await domain.listProjects(c, normalizeProjectType(b.type))).map(project); return { status: 200, body: { cursor: "", data: items, items, projects: items } }; }
      case "CreateProject": { const p = await domain.createProject(c, { name: b.name || "Untitled design system", description: b.description, introText: b.introText || b.intro_text, templateId: b.templateId || b.template_id, templateTitle: b.templateTitle || b.template_title, type: normalizeProjectType(b.type ?? b.projectType ?? b.project_type) }); return { status: 200, body: { name: p.name, project: project(p), projectId: p.id, project_id: p.id } }; }
      case "GetProject": { const p = await domain.getProject(c, idOf(b)); return { status: 200, body: { ...project(p), project: project(p) } }; }
      case "ListFiles": { const id = idOf(b); const all = await domain.listFiles(c, id, b.path ? normalizeProjectPath(b.path) : "", Number.isFinite(Number(b.depth)) ? Number(b.depth) : 1, b.filter); const offset = Math.max(0, Number(b.offset) || 0); const entries = all.slice(offset, offset + 200).map(file); return { status: 200, body: { entries, limit: 200, offset, projectId: id, project_id: id, total: all.length, truncated: offset + 200 < all.length } }; }
      case "GetFile": { const f = await domain.readFile(c, idOf(b), normalizeProjectPath(b.path)); return { status: 200, body: file(f) }; }
      case "WriteFiles": { const id = idOf(b); const files = (Array.isArray(b.files) ? b.files : []).map((v: any) => { const encoded = v.contentBase64 ?? v.bodyBase64 ?? (v.isBase64 || v.is_base64 ? v.content : undefined); return { path: normalizeProjectPath(v.path || v.name), content: Uint8Array.from(Buffer.from(String(encoded ?? v.content ?? v.data ?? ""), encoded !== undefined ? "base64" : "utf8")), contentType: v.contentType || v.content_type || v.mimeType, ifMatch: v.ifMatch || v.if_match }; }); const r = await domain.writeFiles(c, id, files, Array.isArray(b.deletePaths) ? b.deletePaths.map(normalizeProjectPath) : undefined, b.deduplicate === true); return { status: 200, body: { deleted: r.deleted, files: r.files.map(file), projectId: id, project_id: id } }; }
      case "DeleteFiles": { const id = idOf(b); const r = await domain.deleteFiles(c, id, (Array.isArray(b.paths) ? b.paths : []).map(normalizeProjectPath)); return { status: 200, body: { deleted: r.deleted, paths: r.paths, projectId: id, project_id: id } }; }
      case "RecordAsset": { const id = idOf(b); const p = normalizeProjectPath(b.path); const asset = await domain.recordAsset(c, { projectId: id, path: p, name: b.name || p, section: b.section || b.group || "", status: b.status || "recorded", subtitle: b.subtitle || "", chatId: b.chatId || b.chat_id, viewport: b.viewport }); return { status: 200, body: { asset, ok: true, projectId: id, project_id: id } }; }
      case "DeleteAsset": { const id = idOf(b); return { status: 200, body: { deleted: await domain.deleteAsset(c, id, b.name || b.path || "", b.path), ok: true, projectId: id, project_id: id } }; }
      default: return { status: 501, body: { error: { message: `Design sync JSON RPC ${path.slice(JSON_SYNC_PREFIX.length) || "unknown"} is not supported.` } } };
    }
  } catch (e) { if (e instanceof DomainError) return { status: e.status, body: { error: { code: e.code, message: e.message } } }; return { status: 400, body: { error: { message: e instanceof Error ? e.message : String(e) } } }; }
}
