export const SOURCE_COMMIT = "4a3c267e7e22f6636a02542554309cd49cd41e9d";
export const MCP_PROTOCOL_VERSION = "2025-03-26";
export const MCP_TOOL_NAMES = ["list_design_systems", "get_claude_design_prompt", "list_projects", "get_project", "list_files", "read_file", "get_conversation", "list_members", "create_project", "put_conversation", "finalize_plan", "write_files", "copy_files", "delete_files", "render_preview", "create_support_js", "add_member", "update_member_role", "remove_member", "update_sharing"] as const;
export type McpToolName = (typeof MCP_TOOL_NAMES)[number];
export const JSON_SYNC_METHODS = ["ListOrgProjects", "CreateProject", "GetProject", "ListFiles", "GetFile", "WriteFiles", "DeleteFiles", "RecordAsset", "DeleteAsset"] as const;
export const REST_ROUTES = [
  ["GET", "/v1/design/agents"], ["GET", "/v1/design/projects"], ["POST", "/v1/design/projects"],
  ["GET", "/v1/design/projects/:projectId"], ["PATCH", "/v1/design/projects/:projectId"], ["PUT", "/v1/design/projects/:projectId"], ["DELETE", "/v1/design/projects/:projectId"],
  ["GET", "/v1/design/projects/:projectId/messages"], ["POST", "/v1/design/projects/:projectId/messages"], ["GET", "/v1/design/projects/:projectId/events"],
  ["GET", "/v1/design/files"], ["POST", "/v1/design/files"], ["GET", "/v1/design/projects/:projectId/files"], ["GET", "/v1/design/projects/:projectId/files/:path"],
  ["GET", "/v1/design/projects/:projectId/serve/:path"], ["GET", "/v1/design/settings"], ["POST", "/v1/design/settings"], ["GET", "/v1/design/model-selection"], ["POST", "/v1/design/model-selection"], ["POST", "/v1/design/turn-title"]
] as const;
export const CONNECT_IMPLEMENTED_METHODS = ["CreateProject", "GetProject", "ListFiles", "GetFile", "ListProjects", "ListOrgProjects", "WriteFiles", "DeleteFile", "DeleteFiles", "CopyFile", "UpdateSharing"] as const;
export const CONNECT_UNAVAILABLE_METHODS = ["UpdateProject", "DeleteProject", "BundleProject", "ListProjectMembers", "GetProjectData", "UpdateProjectData", "GetChatMessages", "ListChatsForExport", "ExportChatMessages", "CreateClaudeCodeSession", "DuplicateProject", "RemixProject", "CreateTemplateFromProject", "UpdateProjectType", "SetProjectPublished", "UpdateProjectInfo", "UpdateProjectDesignSystems", "PatchDesignSystemBinding", "RefreshBoundDesignSystem", "SetProjectFavorite", "SetProjectThumbnail", "EditFile", "GrepFiles", "CreateFileStream", "WriteFileStream", "AbortFileStream", "UploadFile", "ListProjectAssets", "RecordAsset", "SetAssetStatus", "DeleteAsset", "GetMe", "GetUserSettings", "UpdateUserSettings", "ListUserSkills", "GetUsageStatus", "GetPrepaidBalance", "GetProjectPresence", "UpdateOrgSettings", "GetOrgSettings", "MintPreviewToken", "MintHandoffToken", "MintDesignSyncCode", "CountTokens", "GetParkedMessage", "CancelChat", "Chat", "TrackEvent", "CreateComment", "UpdateComment", "DeleteComment", "ListComments", "CreateCommentReply", "UpdateCommentReply", "DeleteCommentReply", "SendCommentsToChat", "SendMultiplayerMessage", "MarkCommentsRead", "ListExperiences", "TrackExperience", "ExecuteExperienceAction", "LintFiles", "FigmaGetStatus", "GoogleGetStatus", "GithubGetStatus", "McpListConnected", "McpListConnectors", "McpListDesignImportPartners", "McpListTools", "McpStreamTools", "DeleteAccount", "DeleteOrganization", "FigmaCallTool", "McpCallTool", "FigmaDisconnect", "FigmaExchangeCode", "FigmaStartAuth", "GithubDisconnect", "GithubExchangeCode", "GithubStartAuth", "FigmaListTools", "GithubListRepos", "GithubGetTree", "GithubReadFile", "GithubImportRepo", "RenewTurn", "ReleaseTurn"] as const;
export const CONNECT_RPC_METHODS = [...CONNECT_IMPLEMENTED_METHODS, ...CONNECT_UNAVAILABLE_METHODS] as const;
export const CONNECT_METHOD_CONTRACTS = CONNECT_RPC_METHODS.map((name) => CONNECT_IMPLEMENTED_METHODS.includes(name as never) ? { name, status: "implemented" as const } : { name, status: "unavailable" as const, reason: "No product-owned domain capability is exposed for this upstream integration or collaboration operation." });
export const COMPATIBILITY_MANIFEST = { sourceCommit: SOURCE_COMMIT, transports: { rest: { bind: "loopback-only", capabilityAuth: true }, json: { pathPrefix: "/v1/design/anthropic.omelette.api.v1alpha.OmeletteService/", method: "POST" }, connect: { pathPrefix: "/design/anthropic.omelette.api.v1alpha.OmeletteService/", method: "POST", contentTypes: ["application/connect+proto", "application/json"] }, mcp: { path: "/v1/design/mcp", protocolVersion: MCP_PROTOCOL_VERSION, transports: ["stdio", "named-pipe"] } }, restRoutes: REST_ROUTES, jsonSyncMethods: JSON_SYNC_METHODS, connectRpcMethods: CONNECT_METHOD_CONTRACTS, mcpTools: MCP_TOOL_NAMES, contracts: { planTokenTtlMs: 900000, ifMatchHeader: "if-match", ifMatchField: "if_match", roles: ["owner", "editor", "commenter", "viewer"], previewPath: "/_t/local-preview-token/v1/design/projects/:projectId/serve/:path" } } as const;
