import { mkdir, readFile } from "node:fs/promises";
import path from "node:path";
import { writeFileAtomic } from "./atomic";
import { cloneDatabaseState, EMPTY_DATABASE_STATE, type DatabaseState } from "../../project-domain/src/model";
export const DATABASE_SCHEMA_SQL = `PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL); CREATE TABLE account_slots(slot_id TEXT PRIMARY KEY, label TEXT NOT NULL, email TEXT, plan_type TEXT, state TEXT NOT NULL, last_verified_at TEXT, app_server_version TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE projects(id TEXT PRIMARY KEY, owner_slot_id TEXT NOT NULL REFERENCES account_slots(slot_id), name TEXT NOT NULL, description TEXT NOT NULL, version INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, archived_at TEXT, settings_json TEXT NOT NULL); CREATE TABLE project_grants(project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE, slot_id TEXT NOT NULL REFERENCES account_slots(slot_id) ON DELETE CASCADE, role TEXT NOT NULL, PRIMARY KEY(project_id,slot_id)); CREATE TABLE project_files(project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE, path TEXT NOT NULL, content TEXT NOT NULL, version INTEGER NOT NULL, PRIMARY KEY(project_id,path)); CREATE TABLE design_systems(id TEXT PRIMARY KEY, project_id TEXT REFERENCES projects(id) ON DELETE CASCADE, tokens_json TEXT NOT NULL); CREATE TABLE chats(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE); CREATE TABLE chat_messages(id TEXT PRIMARY KEY, chat_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE); CREATE TABLE account_thread_bindings(project_id TEXT NOT NULL, chat_id TEXT NOT NULL, slot_id TEXT NOT NULL REFERENCES account_slots(slot_id), thread_id TEXT NOT NULL, PRIMARY KEY(project_id,chat_id,slot_id)); CREATE TABLE comments(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE, author_slot_id TEXT NOT NULL REFERENCES account_slots(slot_id)); CREATE TABLE migration_receipts(idempotency_key TEXT PRIMARY KEY, source_fingerprint TEXT NOT NULL);`;
export class ProjectDatabase {
  readonly metadataPath: string; readonly walPath: string; private state = cloneDatabaseState(EMPTY_DATABASE_STATE); private loaded = false; private queue: Promise<void> = Promise.resolve();
  constructor(readonly dataRoot: string) { this.metadataPath = path.join(dataRoot, "metadata.json"); this.walPath = path.join(dataRoot, "metadata.wal"); }
  async open(): Promise<void> { if (this.loaded) return; await mkdir(this.dataRoot, { recursive: true }); const [metadata, journal] = await Promise.all([this.readJson(this.metadataPath), this.readJson(this.walPath)]); if (journal && typeof journal === "object" && "state" in journal) { this.state = journal.state as DatabaseState; await writeFileAtomic(this.metadataPath, JSON.stringify(this.state)); await writeFileAtomic(this.walPath, ""); } else if (metadata && typeof metadata === "object") this.state = { ...cloneDatabaseState(EMPTY_DATABASE_STATE), ...(metadata as DatabaseState) }; this.loaded = true; }
  async read(): Promise<DatabaseState> { await this.open(); return cloneDatabaseState(this.state); }
  async transaction(mutate: (state: DatabaseState) => void | Promise<void>): Promise<DatabaseState> { await this.open(); let release!: () => void; const previous = this.queue; this.queue = new Promise((resolve) => { release = resolve; }); await previous; try { const next = cloneDatabaseState(this.state); await mutate(next); await writeFileAtomic(this.walPath, JSON.stringify({ version: 1, state: next })); await writeFileAtomic(this.metadataPath, JSON.stringify(next)); await writeFileAtomic(this.walPath, ""); this.state = next; return cloneDatabaseState(next); } finally { release(); } }
  private async readJson(file: string): Promise<unknown> { try { const text = await readFile(file, "utf8"); return text.trim() ? JSON.parse(text) : undefined; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw error; } }
}
