import { describe, expect, it } from "vitest";
import { MCP_TOOL_NAMES } from "../src/manifest";
import { DesignDomain, DomainError } from "../src/domain";
import { PlanTokenManager } from "../src/plan-tokens";
import { normalizeProjectPath } from "../src/path-policy";
import { handleRestRequest } from "../src/rest-adapter";
import { handleJsonSyncRequest } from "../src/json-sync-adapter";
import { McpBridge } from "../../mcp-bridge/src/server";

const p = (id = "project-fixture") => ({ id, uuid: id, name: "Fixture project", title: "Fixture project", description: "fixture", type: "project" as const, ownerAccountId: "account-fixture", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", canEdit: true, sharing: { scope: "invited" as const, linkPermission: "view" as const, teamCanComment: false, teamCanEdit: false, viewMode: "private" as const }, members: [], fileCount: 1 });
const f = (path = "index.html", value = "<html></html>") => ({ projectId: "project-fixture", path, content: Uint8Array.from(Buffer.from(value)), contentType: "text/html; charset=utf-8", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", version: 1 });
function domain(): DesignDomain { return { addMember: async (_c, _i, m) => m, appendMessage: async () => ({ files: [], messages: [] }), copyFiles: async () => ({ files: [f("copy.html")] }), createProject: async () => p("created"), createSupportJs: async () => f("support.js", "export const support = true;"), deleteAsset: async () => true, deleteFiles: async (_c, _i, paths) => ({ deleted: paths.length, paths }), deleteProject: async () => undefined, getProject: async () => ({ ...p(), messages: [] }), listDesignSystems: async () => [], listFiles: async () => [f()], listMembers: async () => [], listMessages: async () => [], listProjects: async () => [p()], putMessages: async () => [], readFile: async (_c, _i, path) => f(path), recordAsset: async (_c, a) => ({ ...a, uuid: "asset-fixture" }), removeMember: async () => true, renderPreview: async () => ({ projectId: "project-fixture", path: "index.html", contentType: "text/html", render: "browser", validators: [], url: "http://127.0.0.1/preview" }), updateMemberRole: async (_c, _i, accountId, role) => ({ accountId, email: "member@example.invalid", role }), updateProject: async () => p(), updateSharing: async () => p().sharing, writeFiles: async (_c, _i, files) => ({ deleted: 0, files: files.map((x) => f(x.path, Buffer.from(x.content).toString())) }) } as DesignDomain; }

describe("compatibility manifest", () => { it("has the exact 20 MCP tools", () => { expect(MCP_TOOL_NAMES).toHaveLength(20); expect(new Set(MCP_TOOL_NAMES).size).toBe(20); }); it("rejects unsafe paths", () => { expect(() => normalizeProjectPath("../secret")).toThrow(DomainError); expect(() => normalizeProjectPath("C:/secret")).toThrow(DomainError); }); });
describe("plans", () => { it("enforces project and path scope", () => { const m = new PlanTokenManager(); const plan = m.issue("project-fixture", "paths", ["src"]); expect(() => m.validate(plan.token, "other", ["src/a"], "writes")).toThrow("different project"); expect(() => m.validate(plan.token, "project-fixture", ["docs/a"], "writes")).toThrow("does not cover"); expect(() => m.validate(plan.token, "project-fixture", ["src/a"], "writes")).not.toThrow(); }); });
describe("REST, JSON, and MCP", () => { const options = { accountId: "account-fixture", capabilityCheck: () => true }; it("requires loopback", async () => { expect((await handleRestRequest(domain(), { method: "GET", path: "/v1/design/projects", remoteAddress: "192.0.2.1" }, options)).status).toBe(403); }); it("keeps REST shapes", async () => { const r = await handleRestRequest(domain(), { method: "GET", path: "/v1/design/projects", remoteAddress: "127.0.0.1" }, options); expect((r.body as any).projects[0]).toMatchObject({ project_id: "project-fixture", type: 1 }); }); it("dispatches JSON DesignSync", async () => { const r = await handleJsonSyncRequest(domain(), { method: "POST", path: "/v1/design/anthropic.omelette.api.v1alpha.OmeletteService/ListOrgProjects", body: {} }, { accountId: "account-fixture" }); expect(r.status).toBe(200); }); it("requires initialize before tools", async () => { const b = new McpBridge(domain(), { accountId: "account-fixture", previewOrigin: "http://127.0.0.1" }); expect((await b.handle({ id: 1, jsonrpc: "2.0", method: "tools/list" })).error?.code).toBe(-32001); await b.handle({ id: 2, jsonrpc: "2.0", method: "initialize" }); expect(((await b.handle({ id: 3, jsonrpc: "2.0", method: "tools/list" })).result as any).tools).toHaveLength(20); }); });
