import { basename, isAbsolute, normalize } from "node:path";

export const LIMITS = Object.freeze({ responseBytes: 4 * 1024 * 1024, catalogPages: 10_000, catalogModels: 100_000, promptChars: 256_000, historyChars: 2_000_000, attachmentBytes: 25 * 1024 * 1024, queueConcurrency: 8, ndjsonLineBytes: 512 * 1024, harnessArgs: 128, harnessArgChars: 16_384, requestTimeoutMs: 120_000 });
export type FetchLike = (input: string | URL, init?: RequestInit) => Promise<Response>;
export type LoopbackResolver = (hostname: string) => Promise<string[]>;
export class OllamaProtocolError extends Error { constructor(message: string, readonly status?: number) { super(message); this.name = "OllamaProtocolError"; } }
function assertBoundedText(value: unknown, name: string, max: number): string { if (typeof value !== "string" || value.length > max) throw new OllamaProtocolError(`${name} must be a string of at most ${max} characters`); return value; }
function isNumericLoopback(hostname: string): boolean { const host = hostname.toLowerCase().replace(/^\[|\]$/g, ""); return host === "127.0.0.1" || host === "::1"; }
function parseEndpoint(input: string): URL { let url: URL; try { url = new URL(input); } catch { throw new OllamaProtocolError("Ollama endpoint must be a valid URL"); } if (!["http:", "https:"].includes(url.protocol)) throw new OllamaProtocolError("Ollama endpoint must use HTTP or HTTPS"); if (!isNumericLoopback(url.hostname)) throw new OllamaProtocolError("Ollama endpoint must be pinned to a numeric loopback address"); if (url.username || url.password || url.hash) throw new OllamaProtocolError("Ollama endpoint cannot contain credentials or a fragment"); url.pathname = url.pathname.replace(/\/{2,}/g, "/").replace(/\/$/, ""); return url; }
export function validateLoopbackBaseUrl(input: string): URL { return parseEndpoint(input); }
export async function resolveAndPinLoopbackUrl(input: string, resolveHost: LoopbackResolver = async () => []): Promise<URL> { let url: URL; try { url = new URL(input); } catch { throw new OllamaProtocolError("Ollama endpoint must be a valid URL"); } if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || url.hash) throw new OllamaProtocolError("Ollama endpoint has an invalid scheme or credential boundary"); const addresses = isNumericLoopback(url.hostname) ? [url.hostname.replace(/^\[|\]$/g, "")] : await resolveHost(url.hostname); if (addresses.length !== 1 || !isNumericLoopback(addresses[0])) throw new OllamaProtocolError("Ollama endpoint resolution was not exactly one numeric loopback address"); url.hostname = addresses[0].includes(":") ? `[${addresses[0]}]` : addresses[0]; return parseEndpoint(url.toString()); }
function documentedPath(endpoint: string): void { if (!endpoint.startsWith("/") || endpoint.includes("\\") || /%(?:2e|2f|5c|00)/i.test(endpoint)) throw new OllamaProtocolError("API endpoint contains encoded traversal"); const rawPath = endpoint.split("?", 1)[0]; if (/(^|\/)\.{1,2}(?:\/|$)/.test(rawPath)) throw new OllamaProtocolError("API endpoint contains traversal"); if (!/^\/api\/(?:version|tags|ps|pull|chat|catalog(?:\/[A-Za-z0-9._~-]+)?)$/.test(rawPath)) throw new OllamaProtocolError("API endpoint is outside the documented local Ollama path schema"); }
async function boundedBody(response: Response, maxBytes: number, signal?: AbortSignal): Promise<Uint8Array> { const declared = response.headers.get("content-length"); if (declared && (!/^\d+$/.test(declared) || Number(declared) > maxBytes)) throw new OllamaProtocolError(`Response exceeds the ${maxBytes}-byte limit`, response.status); if (!response.body) { const bytes = new Uint8Array(await response.arrayBuffer()); if (bytes.byteLength > maxBytes) throw new OllamaProtocolError(`Response exceeds the ${maxBytes}-byte limit`, response.status); return bytes; } const reader = response.body.getReader(); const cancel = () => { void reader.cancel(); }; signal?.addEventListener("abort", cancel, { once: true }); const chunks: Uint8Array[] = []; let total = 0; try { while (true) { const part = await reader.read(); if (part.done) { if (signal?.aborted) throw new OllamaProtocolError("Ollama response deadline expired", response.status); break; } total += part.value.byteLength; if (total > maxBytes) throw new OllamaProtocolError(`Response exceeds the ${maxBytes}-byte limit`, response.status); chunks.push(part.value); if (signal?.aborted) throw new OllamaProtocolError("Ollama response deadline expired", response.status); } } finally { signal?.removeEventListener("abort", cancel); reader.releaseLock(); } const output = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { output.set(chunk, offset); offset += chunk.byteLength; } return output; }
async function jsonResponse(response: Response, maxBytes: number, signal?: AbortSignal): Promise<Record<string, unknown>> { const text = new TextDecoder().decode(await boundedBody(response, maxBytes, signal)); let value: unknown; try { value = JSON.parse(text); } catch { throw new OllamaProtocolError("Ollama returned malformed JSON", response.status); } if (!value || typeof value !== "object" || Array.isArray(value)) throw new OllamaProtocolError("Ollama returned a JSON object", response.status); return value as Record<string, unknown>; }
async function* ndjsonResponse(response: Response, maxBytes: number, signal?: AbortSignal): AsyncGenerator<Record<string, unknown>> { if (!response.body) { for (const record of parseNdjson(new TextDecoder().decode(await boundedBody(response, maxBytes, signal)))) yield record; return; } const reader = response.body.getReader(); const cancel = () => { void reader.cancel(); }; signal?.addEventListener("abort", cancel, { once: true }); const decoder = new TextDecoder(); let buffer = ""; let total = 0; try { while (true) { const part = await reader.read(); if (part.done) { if (signal?.aborted) throw new OllamaProtocolError("Ollama response deadline expired", response.status); break; } total += part.value.byteLength; if (total > maxBytes) throw new OllamaProtocolError(`Response exceeds the ${maxBytes}-byte limit`, response.status); buffer += decoder.decode(part.value, { stream: true }); if (new TextEncoder().encode(buffer).byteLength > LIMITS.ndjsonLineBytes && !buffer.includes("\n")) throw new OllamaProtocolError("NDJSON line exceeds its bound", response.status); let newline = buffer.indexOf("\n"); while (newline >= 0) { const line = buffer.slice(0, newline).trim(); buffer = buffer.slice(newline + 1); if (line) yield parseNdjsonLine(line); newline = buffer.indexOf("\n"); } if (signal?.aborted) throw new OllamaProtocolError("Ollama response deadline expired", response.status); } buffer += decoder.decode(); if (buffer.trim()) yield parseNdjsonLine(buffer.trim()); } finally { signal?.removeEventListener("abort", cancel); reader.releaseLock(); } }
function parseNdjsonLine(line: string): Record<string, unknown> { if (new TextEncoder().encode(line).byteLength > LIMITS.ndjsonLineBytes) throw new OllamaProtocolError("NDJSON line exceeds its bound"); let value: unknown; try { value = JSON.parse(line); } catch { throw new OllamaProtocolError("Ollama returned malformed NDJSON"); } if (!value || typeof value !== "object" || Array.isArray(value)) throw new OllamaProtocolError("Ollama NDJSON records must be objects"); return value as Record<string, unknown>; }
function* parseNdjson(text: string): Generator<Record<string, unknown>> { for (const line of text.split(/\r?\n/)) if (line.trim()) yield parseNdjsonLine(line.trim()); }

export interface HealthState { healthy: boolean; version?: string; status: number; detail?: string; }
export interface ModelTag { name: string; sizeBytes?: number; digest?: string; modifiedAt?: string; details?: Record<string, unknown>; }
export interface RunningModel extends ModelTag { expiresAt?: string; sizeVramBytes?: number; }
export interface ModelCapabilities { attachmentMimeTypes?: string[]; supportsVision?: boolean; supportsTools?: boolean; }
export interface CatalogVariant { name: string; tag: string; sizeBytes?: number; parameterCount?: number; quantization?: string; contextWindow?: number; requiredMemoryBytes?: number; requiredVramBytes?: number; capabilities?: ModelCapabilities; }
export interface CatalogPage { variants: CatalogVariant[]; next?: string; revision?: string; page?: number; }
export interface CatalogState { variants: CatalogVariant[]; installed: ModelTag[]; running: RunningModel[]; refreshedAt: string; sourceRevision?: string; pageCount: number; complete: boolean; stale: boolean; offline: boolean; error?: string; }
interface RequestLease { response: Response; signal: AbortSignal; close: () => void; }

export class OllamaClient {
  readonly baseUrl: URL;
  constructor(baseUrl = "http://127.0.0.1:11434", private readonly fetchImpl: FetchLike = globalThis.fetch.bind(globalThis), private readonly timeoutMs: number = 15_000, private readonly maxResponseBytes: number = LIMITS.responseBytes) { this.baseUrl = validateLoopbackBaseUrl(baseUrl); if (!Number.isFinite(timeoutMs) || timeoutMs < 1 || timeoutMs > LIMITS.requestTimeoutMs) throw new OllamaProtocolError("Request timeout is outside its bound"); if (!Number.isSafeInteger(maxResponseBytes) || maxResponseBytes < 1 || maxResponseBytes > LIMITS.responseBytes) throw new OllamaProtocolError("Response bound is outside its limit"); }
  private async request(path: string, init: RequestInit = {}): Promise<RequestLease> { documentedPath(path); const endpoint = new URL(path, this.baseUrl); if (endpoint.origin !== this.baseUrl.origin) throw new OllamaProtocolError("API endpoint escaped the local origin"); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), this.timeoutMs); const inherited = init.signal; const abort = () => controller.abort(); if (inherited) { if (inherited.aborted) controller.abort(); else inherited.addEventListener("abort", abort, { once: true }); } try { const headers = new Headers(init.headers); if (!headers.has("accept")) headers.set("accept", "application/json"); const response = await this.fetchImpl(endpoint, { ...init, headers, redirect: "error", signal: controller.signal }); if (!response.ok) throw new OllamaProtocolError(`Ollama HTTP ${response.status}`, response.status); return { response, signal: controller.signal, close: () => { clearTimeout(timer); inherited?.removeEventListener("abort", abort); } }; } catch (error) { clearTimeout(timer); inherited?.removeEventListener("abort", abort); if (error instanceof OllamaProtocolError) throw error; throw new OllamaProtocolError(`Ollama request failed: ${error instanceof Error ? error.message : "unknown error"}`); } }
  async health(): Promise<HealthState> { let lease: RequestLease | undefined; try { lease = await this.request("/api/version"); const body = await jsonResponse(lease.response, this.maxResponseBytes, lease.signal); return { healthy: true, version: typeof body.version === "string" ? body.version : undefined, status: lease.response.status }; } catch (error) { return { healthy: false, status: error instanceof OllamaProtocolError && error.status ? error.status : 0, detail: error instanceof Error ? error.message : "Ollama is unavailable" }; } finally { lease?.close(); } }
  async version(): Promise<string | undefined> { return (await this.health()).version; }
  async installedModels(): Promise<ModelTag[]> { return this.modelList("/api/tags", "installed models"); }
  async runningModels(): Promise<RunningModel[]> { return await this.modelList("/api/ps", "running models") as RunningModel[]; }
  private async modelList(path: string, label: string): Promise<ModelTag[]> { const lease = await this.request(path); try { const body = await jsonResponse(lease.response, this.maxResponseBytes, lease.signal); return parseModelArray(body.models, label); } finally { lease.close(); } }
  async refreshCatalog(path: string, previous?: CatalogState, maxPages: number = LIMITS.catalogPages): Promise<CatalogState> { const variants: CatalogVariant[] = []; const seen = new Set<string>(); let next: string | undefined; let pageCount = 0; let sourceRevision: string | undefined; let expectedPage = 1; try { do { if (++pageCount > maxPages) throw new OllamaProtocolError("Catalog exceeded its page bound"); const lease = await this.request(path, { method: "GET" }); try { const page = parseCatalogPage(await jsonResponse(lease.response, this.maxResponseBytes, lease.signal)); sourceRevision ??= page.revision; if (sourceRevision !== page.revision && page.revision !== undefined) throw new OllamaProtocolError("Catalog revision changed during refresh"); if (page.page !== undefined && page.page !== expectedPage) throw new OllamaProtocolError("Catalog page continuity was not proven"); expectedPage++; for (const variant of page.variants) { const key = modelReference(variant.name, variant.tag); if (seen.has(key)) throw new OllamaProtocolError(`Catalog repeated variant ${key}`); seen.add(key); variants.push(variant); if (variants.length > LIMITS.catalogModels) throw new OllamaProtocolError("Catalog exceeded its variant bound"); } next = page.next; if (next) { documentedPath(next); path = next; } } finally { lease.close(); } } while (next); const [installed, running] = await Promise.all([this.installedModels(), this.runningModels()]); return { variants, installed, running, refreshedAt: new Date().toISOString(), sourceRevision, pageCount, complete: true, stale: false, offline: false }; } catch (error) { return { ...(previous ?? { variants: [], installed: [], running: [], refreshedAt: "", pageCount: 0, complete: false, stale: true, offline: true }), refreshedAt: previous?.refreshedAt ?? "", pageCount, complete: false, stale: true, offline: true, error: error instanceof Error ? error.message : "Catalog refresh failed" }; } }
  async *chat(input: ChatRequest, signal?: AbortSignal): AsyncGenerator<ChatEvent> { const request = validateChatRequest(input); const decoded = decodeAttachments(request.attachments, request.capabilities); const messages = request.messages.map((message) => ({ ...message })); if (decoded.length) { const index = messages.map((message) => message.role).lastIndexOf("user"); if (index < 0) throw new OllamaProtocolError("Vision attachments require a user message"); messages[index] = { ...messages[index], images: decoded.map((item) => item.base64) }; } const lease = await this.request("/api/chat", { method: "POST", headers: { "content-type": "application/json", accept: "application/x-ndjson" }, body: JSON.stringify({ model: request.model, messages, stream: true, options: request.options }), signal }); try { for await (const record of ndjsonResponse(lease.response, this.maxResponseBytes, lease.signal)) { if (typeof record.error === "string") throw new OllamaProtocolError(record.error); yield { message: typeof record.message === "object" && record.message ? record.message as { role?: string; content?: string } : undefined, done: record.done === true, totalDurationNs: typeof record.total_duration === "number" ? record.total_duration : undefined }; } } finally { lease.close(); } }
  async pull(tag: string, onProgress?: (progress: PullProgress) => void | Promise<void>, signal?: AbortSignal): Promise<void> { assertModelTag(tag); const lease = await this.request("/api/pull", { method: "POST", headers: { "content-type": "application/json", accept: "application/x-ndjson" }, body: JSON.stringify({ model: tag, stream: true }), signal }); try { for await (const record of ndjsonResponse(lease.response, this.maxResponseBytes, lease.signal)) { if (typeof record.error === "string") throw new OllamaProtocolError(record.error); await onProgress?.({ status: typeof record.status === "string" ? record.status : "working", completedBytes: typeof record.completed === "number" ? record.completed : undefined, totalBytes: typeof record.total === "number" ? record.total : undefined }); } } finally { lease.close(); } }
}
function parseModelArray(value: unknown, label: string): ModelTag[] { if (!Array.isArray(value)) throw new OllamaProtocolError(`Ollama returned no ${label} array`); return value.map((item, index) => { if (!item || typeof item !== "object" || typeof (item as { name?: unknown }).name !== "string") throw new OllamaProtocolError(`Invalid ${label} entry ${index}`); const source = item as Record<string, unknown>; return { name: source.name as string, sizeBytes: numberOrUndefined(source.size), digest: typeof source.digest === "string" ? source.digest : undefined, modifiedAt: typeof source.modified_at === "string" ? source.modified_at : undefined, details: source.details && typeof source.details === "object" ? source.details as Record<string, unknown> : undefined }; }); }
function parseCatalogPage(value: Record<string, unknown>): CatalogPage { const raw = value.variants ?? value.models ?? value.data; if (!Array.isArray(raw)) throw new OllamaProtocolError("Catalog page has no variant array"); const variants = raw.map((item, index) => { if (!item || typeof item !== "object") throw new OllamaProtocolError(`Invalid catalog variant ${index}`); const source = item as Record<string, unknown>; if (typeof source.name !== "string" || typeof source.tag !== "string") throw new OllamaProtocolError(`Catalog variant ${index} needs name and tag`); return { name: source.name, tag: source.tag, sizeBytes: numberOrUndefined(source.sizeBytes ?? source.size), parameterCount: numberOrUndefined(source.parameterCount ?? source.parameters), quantization: typeof source.quantization === "string" ? source.quantization : undefined, contextWindow: numberOrUndefined(source.contextWindow ?? source.context_length), requiredMemoryBytes: numberOrUndefined(source.requiredMemoryBytes), requiredVramBytes: numberOrUndefined(source.requiredVramBytes), capabilities: source.capabilities && typeof source.capabilities === "object" ? source.capabilities as ModelCapabilities : undefined }; }); return { variants, next: typeof value.next === "string" ? value.next : typeof value.next_page === "string" ? value.next_page : undefined, revision: typeof value.revision === "string" ? value.revision : undefined, page: numberOrUndefined(value.page) }; }
function numberOrUndefined(value: unknown): number | undefined { return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : undefined; }
function assertModelTag(tag: string): void { assertBoundedText(tag, "model tag", 512); if (!/^[A-Za-z0-9._-]+(?:\/[A-Za-z0-9._-]+)*(?::[A-Za-z0-9._-]+)?$/.test(tag)) throw new OllamaProtocolError("Model tag is not valid"); }
function modelReference(name: string, tag?: string): string { const cleanName = name.trim(); const cleanTag = tag?.trim(); return cleanTag && !cleanName.endsWith(`:${cleanTag}`) ? `${cleanName}:${cleanTag}` : cleanName; }

export interface CatalogCache { load(): Promise<CatalogState | undefined>; save(state: CatalogState): Promise<void>; }
export class OfficialCatalogSource { constructor(private readonly client: OllamaClient, private readonly cache?: CatalogCache, private readonly path = "/api/catalog") { documentedPath(path); } async refresh(): Promise<CatalogState> { const previous = await this.cache?.load(); const state = await this.client.refreshCatalog(this.path, previous); if (state.complete) await this.cache?.save(state); return state; } }
export interface HardwareSnapshot { capturedAt: string; ramBytes?: number; gpuModel?: string; vramBytes?: number; driver?: string; freeDiskBytes?: number; architecture?: string; }
export interface HardwareProbe { ramBytes(): Promise<number | undefined>; gpuModel(): Promise<string | undefined>; vramBytes(): Promise<number | undefined>; driver(): Promise<string | undefined>; freeDiskBytes(): Promise<number | undefined>; architecture(): Promise<string | undefined>; }
export class LocalHardwareDetector { constructor(private readonly probe: HardwareProbe) {} async detect(): Promise<HardwareSnapshot> { const [ramBytes, gpuModel, vramBytes, driver, freeDiskBytes, architecture] = await Promise.all([this.probe.ramBytes(), this.probe.gpuModel(), this.probe.vramBytes(), this.probe.driver(), this.probe.freeDiskBytes(), this.probe.architecture()]); return { capturedAt: new Date().toISOString(), ramBytes, gpuModel, vramBytes, driver, freeDiskBytes, architecture }; } }
export type FitVerdict = "Runs well" | "Runs with limits" | "Unlikely" | "Unknown";
export interface FitEvidence { verdict: FitVerdict; capturedAt: string; reasons: string[]; assumptions: string[]; }
export function assessHardwareFit(variant: CatalogVariant, hardware: HardwareSnapshot): FitEvidence { const reasons: string[] = []; const assumptions: string[] = []; if (!variant.sizeBytes || !variant.requiredMemoryBytes || !hardware.ramBytes || hardware.freeDiskBytes === undefined) return { verdict: "Unknown", capturedAt: hardware.capturedAt, reasons: ["Exact blob size, required memory, RAM, and free disk are required"], assumptions }; const requiredDisk = Math.ceil(variant.sizeBytes * 1.2); if (hardware.freeDiskBytes < requiredDisk) return { verdict: "Unlikely", capturedAt: hardware.capturedAt, reasons: [`Free disk ${hardware.freeDiskBytes} is below conservative requirement ${requiredDisk}`], assumptions }; if (hardware.ramBytes < variant.requiredMemoryBytes) return { verdict: "Unlikely", capturedAt: hardware.capturedAt, reasons: [`RAM ${hardware.ramBytes} is below required memory ${variant.requiredMemoryBytes}`], assumptions }; if (variant.requiredVramBytes !== undefined) { if (hardware.vramBytes === undefined) return { verdict: "Unknown", capturedAt: hardware.capturedAt, reasons: ["Variant declares VRAM requirement but usable VRAM was not detected"], assumptions }; if (hardware.vramBytes < variant.requiredVramBytes) return { verdict: "Unlikely", capturedAt: hardware.capturedAt, reasons: [`VRAM ${hardware.vramBytes} is below requirement ${variant.requiredVramBytes}`], assumptions }; } if (hardware.ramBytes < variant.requiredMemoryBytes * 1.25) return { verdict: "Runs with limits", capturedAt: hardware.capturedAt, reasons: ["RAM is close to the declared requirement"], assumptions }; if (variant.requiredVramBytes !== undefined && hardware.vramBytes !== undefined && hardware.vramBytes < variant.requiredVramBytes * 1.25) return { verdict: "Runs with limits", capturedAt: hardware.capturedAt, reasons: ["VRAM is close to the declared requirement"], assumptions }; assumptions.push("Verdict uses published metadata and detected hardware only; it does not infer capability from the model name"); return { verdict: "Runs well", capturedAt: hardware.capturedAt, reasons: ["RAM, storage, and declared accelerator requirements have conservative headroom"], assumptions }; }
export function reconcileCatalog(state: CatalogState): Array<CatalogVariant & { installed: boolean; running: boolean }> { const installed = new Set(state.installed.map((item) => item.name)); const running = new Set(state.running.map((item) => item.name)); return state.variants.map((variant) => { const reference = modelReference(variant.name, variant.tag); return { ...variant, installed: installed.has(reference), running: running.has(reference) }; }); }

export interface PullProgress { status: string; completedBytes?: number; totalBytes?: number; }
export type PullStatus = "queued" | "running" | "paused" | "pulled" | "skipped" | "cancelled" | "failed";
export interface PullRecord { id: string; tag: string; status: PullStatus; progress?: PullProgress; error?: string; updatedAt: string; }
export interface PullStateStore { read(): Promise<PullRecord[]>; writeAtomic(records: PullRecord[]): Promise<void>; }
function cloneRecords(records: PullRecord[]): PullRecord[] { return records.map((record) => ({ ...record, progress: record.progress && { ...record.progress } })); }
export class MemoryPullStateStore implements PullStateStore { private records: PullRecord[] = []; async read(): Promise<PullRecord[]> { return cloneRecords(this.records); } async writeAtomic(records: PullRecord[]): Promise<void> { this.records = cloneRecords(records); } }
export class SerializedPullStateStore implements PullStateStore { constructor(private readonly readText: () => Promise<string>, private readonly writeTextAtomic: (text: string) => Promise<void>, private readonly maxBytes = LIMITS.responseBytes) {} async read(): Promise<PullRecord[]> { const text = await this.readText(); if (new TextEncoder().encode(text).byteLength > this.maxBytes) throw new OllamaProtocolError("Pull state exceeds its byte bound"); if (!text.trim()) return []; let value: unknown; try { value = JSON.parse(text); } catch { throw new OllamaProtocolError("Pull state is malformed JSON"); } if (!Array.isArray(value)) throw new OllamaProtocolError("Pull state must be an array"); return value.map((item, index) => { if (!item || typeof item !== "object") throw new OllamaProtocolError(`Invalid pull state entry ${index}`); const record = item as Record<string, unknown>; const statuses: PullStatus[] = ["queued", "running", "paused", "pulled", "skipped", "cancelled", "failed"]; if (typeof record.id !== "string" || typeof record.tag !== "string" || !statuses.includes(record.status as PullStatus) || typeof record.updatedAt !== "string") throw new OllamaProtocolError(`Invalid pull state entry ${index}`); return { id: record.id, tag: record.tag, status: record.status as PullStatus, updatedAt: record.updatedAt, ...(record.progress && typeof record.progress === "object" ? { progress: record.progress as PullProgress } : {}), ...(typeof record.error === "string" ? { error: record.error } : {}) }; }); } async writeAtomic(records: PullRecord[]): Promise<void> { const text = JSON.stringify(records); if (new TextEncoder().encode(text).byteLength > this.maxBytes) throw new OllamaProtocolError("Pull state exceeds its byte bound"); await this.writeTextAtomic(text); } }
export class PullQueue {
  private readonly active = new Map<string, AbortController>(); private readonly intent = new Map<string, "paused" | "cancelled">(); private writeChain: Promise<void> = Promise.resolve();
  constructor(private readonly client: OllamaClient, private readonly store: PullStateStore, private readonly concurrency = 2) { if (!Number.isInteger(concurrency) || concurrency < 1 || concurrency > LIMITS.queueConcurrency) throw new OllamaProtocolError("Pull concurrency is outside its bound"); }
  private async persist(records: PullRecord[]): Promise<void> { const snapshot = cloneRecords(records); this.writeChain = this.writeChain.then(() => this.store.writeAtomic(snapshot)); await this.writeChain; }
  async enqueue(tags: string[]): Promise<PullRecord[]> { const records = await this.store.read(); const existing = new Set(records.map((record) => record.tag)); const now = new Date().toISOString(); for (const tag of tags) { assertModelTag(tag); if (!existing.has(tag)) { records.push({ id: crypto.randomUUID(), tag, status: "queued", updatedAt: now }); existing.add(tag); } } await this.persist(records); return records; }
  async pause(id: string): Promise<void> { this.intent.set(id, "paused"); this.active.get(id)?.abort(); const records = await this.store.read(); const record = records.find((item) => item.id === id); if (record && ["queued", "running"].includes(record.status)) { record.status = "paused"; record.updatedAt = new Date().toISOString(); await this.persist(records); } }
  async cancel(id: string): Promise<void> { this.intent.set(id, "cancelled"); this.active.get(id)?.abort(); const records = await this.store.read(); const record = records.find((item) => item.id === id); if (record && !["pulled", "cancelled"].includes(record.status)) { record.status = "cancelled"; record.updatedAt = new Date().toISOString(); await this.persist(records); } }
  async resume(id: string): Promise<void> { this.intent.delete(id); const records = await this.store.read(); const record = records.find((item) => item.id === id); if (!record || !["paused", "cancelled", "failed"].includes(record.status)) return; record.status = "queued"; record.error = undefined; record.updatedAt = new Date().toISOString(); await this.persist(records); }
  async run(): Promise<PullRecord[]> { const records = await this.store.read(); for (const record of records) if (record.status === "running") record.status = "queued"; await this.persist(records); const candidates = records.filter((record) => record.status === "queued" || record.status === "failed"); let cursor = 0; const worker = async () => { while (cursor < candidates.length) { const record = candidates[cursor++]; const controller = new AbortController(); this.active.set(record.id, controller); record.status = "running"; record.error = undefined; record.updatedAt = new Date().toISOString(); await this.persist(records); try { await this.client.pull(record.tag, async (progress) => { record.progress = progress; record.updatedAt = new Date().toISOString(); await this.persist(records); }, controller.signal); if (!this.intent.has(record.id)) record.status = "pulled"; } catch (error) { const intent = this.intent.get(record.id); record.status = intent ?? (controller.signal.aborted ? "cancelled" : "failed"); record.error = intent ? undefined : error instanceof Error ? error.message : "Pull failed"; } finally { this.active.delete(record.id); this.intent.delete(record.id); record.updatedAt = new Date().toISOString(); await this.persist(records); } } }; await Promise.all(Array.from({ length: Math.min(this.concurrency, candidates.length) }, () => worker())); return this.store.read(); }
}

export interface ChatMessage { role: "system" | "user" | "assistant" | "tool"; content: string; images?: string[]; }
export interface ChatAttachment { mimeType: string; base64: string; bytes: number; }
export interface ChatRequest { model: string; messages: ChatMessage[]; options?: Record<string, number | string | boolean | string[]>; attachments?: ChatAttachment[]; capabilities?: ModelCapabilities; }
export interface ChatEvent { message?: { role?: string; content?: string }; done: boolean; totalDurationNs?: number; }
const CHAT_OPTIONS = new Set(["temperature", "top_k", "top_p", "min_p", "typical_p", "repeat_last_n", "repeat_penalty", "presence_penalty", "frequency_penalty", "num_ctx", "num_predict", "seed", "num_batch", "num_gpu", "main_gpu", "num_thread", "use_mmap", "use_mlock", "stop"]);
function validateChatRequest(input: ChatRequest): ChatRequest { assertModelTag(input.model); if (!Array.isArray(input.messages) || input.messages.length === 0) throw new OllamaProtocolError("Chat needs at least one message"); const messages = input.messages.map((message) => { if (!message || !["system", "user", "assistant", "tool"].includes(message.role) || typeof message.content !== "string") throw new OllamaProtocolError("Chat message has an invalid role or content"); return { role: message.role, content: assertBoundedText(message.content, "message content", LIMITS.promptChars), ...(message.images ? { images: [...message.images] } : {}) }; }); if (messages.reduce((sum, message) => sum + message.content.length, 0) > LIMITS.historyChars) throw new OllamaProtocolError("Chat history exceeds its bound"); if (input.options) for (const [key, value] of Object.entries(input.options)) { if (!CHAT_OPTIONS.has(key) || (typeof value === "number" && !Number.isFinite(value)) || (typeof value === "string" && value.length > 2_048) || (Array.isArray(value) && (value.length > 32 || value.some((item) => typeof item !== "string" || item.length > 2_048)))) throw new OllamaProtocolError(`Chat option ${key} is invalid`); } return { ...input, messages }; }
function decodeBase64(value: string): Uint8Array { if (!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value)) throw new OllamaProtocolError("Attachment is not valid base64"); try { const binary = atob(value); return Uint8Array.from(binary, (character) => character.charCodeAt(0)); } catch { throw new OllamaProtocolError("Attachment is not valid base64"); } }
function signatureMatches(mimeType: string, bytes: Uint8Array): boolean { if (mimeType === "image/png") return bytes.length >= 8 && bytes.slice(0, 8).every((value, index) => value === [137, 80, 78, 71, 13, 10, 26, 10][index]); if (mimeType === "image/jpeg") return bytes.length >= 3 && bytes[0] === 255 && bytes[1] === 216 && bytes[2] === 255; if (mimeType === "image/gif") return new TextDecoder().decode(bytes.slice(0, 6)) === "GIF89a" || new TextDecoder().decode(bytes.slice(0, 6)) === "GIF87a"; if (mimeType === "image/webp") return new TextDecoder().decode(bytes.slice(0, 4)) === "RIFF" && new TextDecoder().decode(bytes.slice(8, 12)) === "WEBP"; return false; }
export function decodeAttachments(attachments: ChatAttachment[] | undefined, capabilities: ModelCapabilities | undefined): ChatAttachment[] { if (!attachments?.length) return []; if (!capabilities) throw new OllamaProtocolError("Attachment capability metadata is unavailable"); return attachments.map((attachment) => { if (!Number.isSafeInteger(attachment.bytes) || attachment.bytes < 0 || attachment.bytes > LIMITS.attachmentBytes || !capabilities.attachmentMimeTypes?.includes(attachment.mimeType)) throw new OllamaProtocolError(`Model does not support attachment type ${attachment.mimeType}`); const bytes = decodeBase64(attachment.base64); if (bytes.byteLength !== attachment.bytes || !signatureMatches(attachment.mimeType, bytes)) throw new OllamaProtocolError("Attachment bytes do not match the declared type or size"); return { ...attachment, bytes: bytes.byteLength }; }); }
export function assertAttachmentCapabilities(attachments: ChatAttachment[] | undefined, capabilities: ModelCapabilities | undefined): void { decodeAttachments(attachments, capabilities); }

export interface HarnessProfile { id: string; label: string; executablePath: string; args: string[]; workingDirectory: string; environmentKeys: string[]; modelTag: string; }
export interface ReviewedHarnessProfile extends HarnessProfile { reviewed: true; }
export class ProductHarnessRegistry { private readonly profiles = new Map<string, ReviewedHarnessProfile>(); constructor(entries: ReviewedHarnessProfile[]) { for (const entry of entries) { validateHarnessShape(entry); this.profiles.set(entry.id, cloneReviewedHarness(entry)); } } get(id: string): ReviewedHarnessProfile | undefined { const profile = this.profiles.get(id); return profile && cloneReviewedHarness(profile); } accepts(profile: HarnessProfile): boolean { const reviewed = this.profiles.get(profile.id); return !!reviewed && JSON.stringify(reviewed) === JSON.stringify({ ...profile, reviewed: true }); } }
function validateHarnessShape(profile: HarnessProfile): void { assertBoundedText(profile.id, "profile id", 128); assertBoundedText(profile.label, "profile label", 256); assertModelTag(profile.modelTag); if (!isAbsolute(profile.executablePath) || !isAbsolute(profile.workingDirectory)) throw new OllamaProtocolError("Harness executable and working directory must be absolute paths"); const executableName = basename(profile.executablePath).toLowerCase(); if (!/\.(?:exe|com)$/i.test(profile.executablePath) || ["cmd.exe", "powershell.exe", "pwsh.exe", "wscript.exe", "cscript.exe"].includes(executableName)) throw new OllamaProtocolError("Harness executable must be a reviewed executable file, not a shell host"); if (!Array.isArray(profile.args) || profile.args.length > LIMITS.harnessArgs) throw new OllamaProtocolError("Harness arguments exceed their bound"); for (const arg of profile.args) { assertBoundedText(arg, "harness argument", LIMITS.harnessArgChars); if (/[\r\n;&|`$<>]/.test(arg)) throw new OllamaProtocolError("Harness arguments cannot contain shell syntax"); } if (!Array.isArray(profile.environmentKeys) || profile.environmentKeys.some((key) => !/^[A-Z_][A-Z0-9_]{0,31}$/.test(key))) throw new OllamaProtocolError("Harness environment keys are invalid"); }
export function validateHarnessProfile(profile: HarnessProfile): HarnessProfile { validateHarnessShape(profile); return cloneHarness(profile); }
function cloneHarness(profile: HarnessProfile): HarnessProfile { return { ...profile, executablePath: normalize(profile.executablePath), workingDirectory: normalize(profile.workingDirectory), args: [...profile.args], environmentKeys: [...profile.environmentKeys] }; }
function cloneReviewedHarness(profile: ReviewedHarnessProfile): ReviewedHarnessProfile { return { ...cloneHarness(profile), reviewed: true }; }
function redactedArgs(args: string[]): string[] { const output: string[] = []; let redactNext = false; for (const arg of args) { if (redactNext) { output.push("[redacted]"); redactNext = false; continue; } const split = /^(--?)(token|password|secret|key)$/i.exec(arg); const joined = /^(--?)(token|password|secret|key)=(.*)$/i.exec(arg); if (joined) output.push(`${joined[1]}${joined[2]}=[redacted]`); else { output.push(arg); if (split) redactNext = true; } } return output; }
export interface HarnessPreview { profileId: string; executablePath: string; args: string[]; workingDirectory: string; environmentKeys: string[]; modelTag: string; blockers: string[]; }
export function createHarnessPreview(profile: HarnessProfile, registry: ProductHarnessRegistry): HarnessPreview { const valid = validateHarnessProfile(profile); if (!registry.accepts(valid)) throw new OllamaProtocolError("Harness profile is not in the reviewed product registry"); return { profileId: valid.id, executablePath: valid.executablePath, args: redactedArgs(valid.args), workingDirectory: valid.workingDirectory, environmentKeys: [...valid.environmentKeys], modelTag: valid.modelTag, blockers: [] }; }
export interface HarnessHandle { id: string; processId?: number; }
export interface HarnessLauncher { launch(profile: HarnessProfile, environment: Record<string, string>, signal: AbortSignal): Promise<HarnessHandle>; health(handle: HarnessHandle, signal: AbortSignal): Promise<boolean>; terminate(handle: HarnessHandle): Promise<void>; }
export interface HarnessSnapshot { id: string; profile: HarnessProfile; createdAt: string; }
export interface SnapshotStore { save(snapshot: HarnessSnapshot): Promise<void>; latest(profileId: string): Promise<HarnessSnapshot | undefined>; }
export class HarnessManager { private readonly profiles = new Map<string, HarnessProfile>(); constructor(private readonly launcher: HarnessLauncher, private readonly snapshots: SnapshotStore, private readonly environment: (keys: string[]) => Promise<Record<string, string>>, private readonly registry: ProductHarnessRegistry) {} register(profile: HarnessProfile): HarnessPreview { const valid = validateHarnessProfile(profile); if (!this.registry.accepts(valid)) throw new OllamaProtocolError("Harness profile is not in the reviewed product registry"); this.profiles.set(valid.id, valid); return createHarnessPreview(valid, this.registry); } preview(id: string): HarnessPreview { const profile = this.profiles.get(id); if (!profile) throw new OllamaProtocolError("Harness profile is not registered"); return createHarnessPreview(profile, this.registry); } async restore(id: string): Promise<HarnessProfile> { const snapshot = await this.snapshots.latest(id); if (!snapshot) throw new OllamaProtocolError("No harness snapshot is available"); this.profiles.set(id, cloneHarness(snapshot.profile)); return cloneHarness(snapshot.profile); } async launch(id: string): Promise<HarnessHandle> { const profile = this.profiles.get(id); if (!profile) throw new OllamaProtocolError("Harness profile is not registered"); const prior = await this.snapshots.latest(id); await this.snapshots.save({ id: crypto.randomUUID(), profile: cloneHarness(profile), createdAt: new Date().toISOString() }); const rawEnvironment = await this.environment(profile.environmentKeys); const environment = Object.fromEntries(profile.environmentKeys.flatMap((key) => typeof rawEnvironment[key] === "string" ? [[key, rawEnvironment[key]]] : [])); const controller = new AbortController(); let handle: HarnessHandle | undefined; try { handle = await this.launcher.launch(profile, environment, controller.signal); if (await this.launcher.health(handle, controller.signal)) return handle; } catch { /* rollback below */ } if (handle) await this.launcher.terminate(handle); if (prior) this.profiles.set(id, cloneHarness(prior.profile)); throw new OllamaProtocolError("Harness health check failed; the profile was rolled back"); } }

export const __test = { parseCatalogPage, parseNdjsonLine, redactedArgs, modelReference };
