import { createHash, randomUUID } from "node:crypto";
import { DomainError, ProjectDomainService } from "../../project-domain/src/index";
import { nowIso, type MigrationReceipt } from "../../project-domain/src/model";
export const MIGRATION_FORMAT = "claude-design-desktop-import-v1"; export const SOURCE_COMMIT = "4a3c267e7e22f6636a02542554309cd49cd41e9d";
const MAX_ENTRY_BYTES = 50_000_000; const MAX_TOTAL_BYTES = 2_000_000_000; const FORBIDDEN = /(^|\/)(request-logs?|headers?|responses?|proxy|cached-assets?|browser-state|gateway|oauth|telemetry|credentials?)(\/|\.|$)/i;
export type ArchiveEntry = { name: string; bytes: Uint8Array; symlink?: boolean; reparsePoint?: boolean };
export type ImportManifest = { format: typeof MIGRATION_FORMAT; schemaVersion: 1; sourceProductVersion: string; sourceCommit: string; sourceDatabaseSha256: string; exportedAt: string; idempotencyKey: string; recordCounts: Record<string, number>; exclusionCounts: Record<string, number>; fileHashes: Record<string, string> };
export type MigrationArchive = { entries: AsyncIterable<ArchiveEntry> | Iterable<ArchiveEntry>; manifest: ImportManifest };
export type MigrationPreflight = { format: typeof MIGRATION_FORMAT; sourceFingerprint: string; manifest: ImportManifest; projects: Array<{ legacyId: string; name: string; ownerKey: string | null; fileCount: number }>; members: string[]; excluded: Array<{ name: string; reason: string }>; errors: string[]; totalBytes: number };
export type OwnerMapping = Record<string, string | null>;
export async function inspectMigrationArchive(archive: MigrationArchive): Promise<MigrationPreflight> { const scanned = await scan(archive); const errors = [...scanned.errors]; const projects = new Map<string, { legacyId: string; name: string; ownerKey: string | null; fileCount: number }>(); const members = new Set<string>(); for (const entry of scanned.safeEntries) { const parts = entry.name.split("/"); if (parts[0] !== "projects" || parts.length < 3) continue; const row = projects.get(parts[1]) || { legacyId: parts[1], name: parts[1], ownerKey: null, fileCount: 0 }; if (parts[2] === "project.json") { try { const data = JSON.parse(Buffer.from(entry.bytes).toString("utf8")) as { name?: unknown; ownerKey?: unknown; members?: unknown }; if (typeof data.name === "string") row.name = data.name; if (typeof data.ownerKey === "string") { row.ownerKey = data.ownerKey; members.add(data.ownerKey); } if (Array.isArray(data.members)) for (const member of data.members) if (typeof member === "string") members.add(member); } catch { errors.push(`Invalid JSON in ${entry.name}.`); } } else if (parts[2] === "files") row.fileCount += 1; projects.set(parts[1], row); } if (archive.manifest.format !== MIGRATION_FORMAT) errors.push(`Unsupported archive format: ${archive.manifest.format}.`); if (archive.manifest.schemaVersion !== 1) errors.push(`Unsupported archive schema version: ${archive.manifest.schemaVersion}.`); return { format: MIGRATION_FORMAT, sourceFingerprint: fingerprint(archive.manifest), manifest: archive.manifest, projects: [...projects.values()], members: [...members], excluded: scanned.excluded, errors, totalBytes: scanned.totalBytes }; }
export async function importMigrationArchive(service: ProjectDomainService, archive: MigrationArchive, mapping: OwnerMapping, options: { idempotencyKey: string; allowUnresolvedOwners?: boolean }): Promise<MigrationReceipt> { const preflight = await inspectMigrationArchive(archive); if (preflight.errors.length) throw new DomainError("MIGRATION_INVALID", preflight.errors.join(" ")); if (options.idempotencyKey !== archive.manifest.idempotencyKey) throw new DomainError("MIGRATION_IDEMPOTENCY_KEY", "The idempotency key does not match the manifest."); const current = (await service.databaseState()).receipts.find((r) => r.idempotencyKey === options.idempotencyKey); if (current) { if (current.sourceFingerprint !== preflight.sourceFingerprint) throw new DomainError("MIGRATION_IDEMPOTENCY_CONFLICT", "The idempotency key was used for another archive."); return current; } const scanned = await scan(archive); const accounts = await service.listAccounts(); const owner = (key: string | null): string | null => { const slot = key ? mapping[key] : null; return slot && accounts.some((a) => a.slotId === slot) ? slot : null; }; const unresolved = preflight.projects.filter((p) => !owner(p.ownerKey)); if (unresolved.length && !options.allowUnresolvedOwners) throw new DomainError("MIGRATION_OWNER_MAPPING", `Missing account mapping for ${unresolved.length} project owner(s).`); const map: Record<string, string> = {}; let fileCount = 0; for (const legacy of preflight.projects) { const slot = owner(legacy.ownerKey); if (!slot) continue; let id = safeId(legacy.legacyId); if ((await service.listProjects(slot, true)).some((p) => p.id === id)) id = `import_${randomUUID()}`; const created = await service.createProject({ id, name: legacy.name, ownerSlotId: slot, description: "Imported project" }); map[legacy.legacyId] = created.id; for (const entry of scanned.safeEntries) { const prefix = `projects/${legacy.legacyId}/files/`; if (!entry.name.startsWith(prefix)) continue; const relativePath = entry.name.slice(prefix.length); if (!relativePath) continue; await service.writeFile({ projectId: created.id, actorSlotId: slot, path: relativePath, content: Buffer.from(entry.bytes).toString("utf8") }); fileCount += 1; } } const receipt: MigrationReceipt = { idempotencyKey: options.idempotencyKey, sourceFingerprint: preflight.sourceFingerprint, sourceProductVersion: archive.manifest.sourceProductVersion, sourceCommit: archive.manifest.sourceCommit, importedAt: nowIso(), projectCount: Object.keys(map).length, fileCount, unresolvedOwnerCount: unresolved.length, projectIdMap: map, excludedCounts: archive.manifest.exclusionCounts }; await service.addMigrationReceipt(receipt); return receipt; }
async function scan(archive: MigrationArchive): Promise<{ safeEntries: ArchiveEntry[]; excluded: MigrationPreflight["excluded"]; errors: string[]; totalBytes: number }> { const safeEntries: ArchiveEntry[] = []; const excluded: MigrationPreflight["excluded"] = []; const errors: string[] = []; const names = new Set<string>(); let totalBytes = 0; for await (const raw of archive.entries) { const name = raw.name.replaceAll("\\", "/"); if (!name || name.startsWith("/") || /^[a-zA-Z]:/.test(name) || name.split("/").some((part) => part === ".." || part === "")) { errors.push(`Unsafe archive path: ${raw.name}.`); continue; } if (names.has(name)) { errors.push(`Duplicate archive path: ${name}.`); continue; } names.add(name); if (raw.symlink || raw.reparsePoint) { errors.push(`Links are not accepted: ${name}.`); continue; } if (raw.bytes.byteLength > MAX_ENTRY_BYTES) { errors.push(`Archive entry is too large: ${name}.`); continue; } totalBytes += raw.bytes.byteLength; if (totalBytes > MAX_TOTAL_BYTES) { errors.push("Archive exceeds the total byte limit."); continue; } if (FORBIDDEN.test(name)) { excluded.push({ name, reason: "secret, browser, gateway, request-log, cache, or telemetry data is never imported" }); continue; } safeEntries.push({ ...raw, name }); } return { safeEntries, excluded, errors, totalBytes }; }
function fingerprint(manifest: ImportManifest): string { return createHash("sha256").update(JSON.stringify({ format: manifest.format, schemaVersion: manifest.schemaVersion, sourceDatabaseSha256: manifest.sourceDatabaseSha256, idempotencyKey: manifest.idempotencyKey, fileHashes: manifest.fileHashes })).digest("hex"); }
function safeId(value: string): string { const clean = value.replace(/[^a-zA-Z0-9._-]/g, "_").replace(/^[-.]+/, "").slice(0, 100); return clean || `import_${randomUUID()}`; }
